# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# A sample workflow which sets up periodic OSV-Scanner scanning for vulnerabilities,
# in addition to a PR check which fails if new vulnerabilities are introduced.
#
# For more examples and options, including how to ignore specific vulnerabilities,
# see https://google.github.io/osv-scanner/github-action/

name: OSV-Scanner

on:
  pull_request:
    branches: [ "master" ]
  merge_group:
    branches: [ "master" ]
  schedule:
    - cron: '13 23 * * 0'
  push:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  # Read commit contents
  contents: read
  actions: read
  
jobs:
  scan-scheduled:
    permissions:
      # Require writing security events to upload SARIF file to security tab
      security-events: write
      # Read commit contents
      contents: read
      actions: read
    if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@c51854704019a247608d928f370c98740469d4b5" # v2.3.5
    with:
      # Example of specifying custom arguments
      scan-args: |-
        -r
        --skip-git
        ./
  scan-pr:
    permissions:
      # Require writing security events to upload SARIF file to security tab
      security-events: write
      # Read commit contents
      contents: read
      actions: read
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@c5996e0193a3df57d695c1b8a1dec2a4c62e8730" # v2.3.3
    with:
      # Example of specifying custom arguments
      scan-args: |-
        -r
        --skip-git
        ./
